name: bah_easy_cpr
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  # https://pub.dev/packages/multiple_result
  multiple_result: ^5.1.0
  # https://pub.dev/packages/logging
  logging: ^1.2.0
  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.3.1
  # https://pub.dev/packages/flutter_screenutil
  flutter_screenutil: ^5.9.0
  # https://pub.dev/packages/flutter_svg
  flutter_svg: ^2.0.10+1
  # https://pub.dev/packages/permission_handler
  permission_handler: ^11.3.1
  # https://pub.dev/packages/collection
  collection:
    ^1.18.0
    # https://pub.dev/packages/animations
  animations: ^2.0.11
  # https://pub.dev/packages/rxdart
  rxdart: ^0.27.7
  # https://pub.dev/packages/freezed_annotation
  freezed_annotation: ^2.4.1
  # https://pub.dev/packages/flutter_riverpod
  flutter_riverpod: ^2.5.1
  # https://pub.dev/packages/shared_preferences
  shared_preferences: ^2.2.3
  # https://pub.dev/packages/json_annotation
  json_annotation: ^4.9.0
  # https://pub.dev/packages/jiffy
  jiffy: ^6.3.0
  # https://pub.dev/packages/injectable
  injectable: ^2.4.1
  # https://docs.hivedb.dev
  hive_flutter: ^1.1.0
  # https://pub.dev/packages/package_info_plus
  package_info_plus: ^8.0.0
  # https://pub.dev/packages/device_info_plus
  device_info_plus: ^10.1.0
  # https://pub.dev/packages/url_launcher
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner:
  flutter_gen:
  flutter_gen_runner:
  # https://pub.dev/packages/freezed
  freezed: ^2.5.2
  # https://pub.dev/packages/retrofit_generator
  retrofit_generator: ^8.1.0
  # https://pub.dev/packages/json_serializable
  json_serializable: ^6.8.0
  # https://pub.dev/packages/envied_generator
  envied_generator: ^0.5.4+1
  # https://pub.dev/packages/flutter_launcher_icons
  flutter_launcher_icons: ^0.13.1
  # https://pub.dev/packages/change_app_package_name
  change_app_package_name: ^1.3.0
  # https://pub.dev/packages/husky
  husky: ^0.1.7

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/imgs/

  fonts:
    - family: NotoSansThai
      fonts:
        - asset: google_fonts/NotoSansThai-Bold.ttf
        - asset: google_fonts/NotoSansThai-Medium.ttf
        - asset: google_fonts/NotoSansThai-Regular.ttf

flutter_gen:
  output: lib/generated/
  integrations:
    flutter_svg: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imgs/logo_app_512.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
