#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

# Check if commit message matches the format "<Type>: <message>" or "Merge branch ..."
if ! echo "$commit_msg" | grep -qE "^(Fix|Feat|Docs|Style|Refactor|Perf|Test|Chore): .*|^Merge .*"; then
    echo "Invalid commit message format. Please use: <Type>: <message> or Merge branch ..."
    exit 1  # Exit with error to prevent commit
fi

exit 0  # Allow commit if message format is correct
