#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Define the regex for branch naming convention
BRANCH_REGEX="^(feature|bugfix|hotfix|release|dev|setup|base|refactor)\/[a-zA-Z0-9._-]+$"

# Get the current branch name
BRANCH_NAME=$(git symbolic-ref --short HEAD)

if [[ ! $BRANCH_NAME =~ $BRANCH_REGEX ]]; then
    echo "Error: Branch name '$BRANCH_NAME' does not follow the naming convention."
    echo "Please use one of the following prefixes: feature/, bugfix/, hotfix/, release/, dev/, setup/, base/, refactor/"
    exit 1
fi
